# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9814f8e0a1701602ca454bf591e828cebdf7a955d9811d0ac19d7f49ba2a4555ac2b8f5a5ba0b2284e46a0c0fdde46ebb8bbefb3b3b181c51b86abc096586505

test:
  secret_key_base: 8791d8da3e5ebd233a9e44ee0b901261fb1f5028a62025ea5451b5175d1d4750f05b13e9a4c49b3a0049207753551ae2627377f4575c3be21f16b74063ea4a49

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
